### ISSUE TITLE
BRUH

### ISSUE THREAD

**Issue by adeel-dot** [ccxmIcal/Roblox-Server-IP-Grabber#1]
man i know this is a account stealer im not stupid man i know what a roblox cookie a roblox cookie is ur entire acc so if u give it to anyone thats smart egnouth to know what it is say byebye to ur acc so no im not even going to test it out and yes i did not event test it and i know it steals ur account now let me go and release my crazynesskoWEIFNJI OCUDFJOUWEA JIGYPHRFTGCV

**Comment by adeel-dot** [comment]
ED

**Comment by ccxmIcal** [comment]
> man i know this is a account stealer im not stupid man i know what a roblox cookie a roblox cookie is ur entire acc so if u give it to anyone thats smart egnouth to know what it is say byebye to ur acc so no im not even going to test it out and yes i did not event test it and i know it steals ur account now let me go and release my crazynesskoWEIFNJI OCUDFJOUWEA JIGYPHRFTGCV 

You can see the source code yourself.

**Comment by adeel-dot** [comment]
bro ima not look at the source i just know its a logger because you have to put ur roblox cookie in and ur roblox cookie is ur entire account so its a logger i just know
